### ISSUE TITLE
Contract file not found

### ISSUE THREAD

**Issue by chingswy** [GUO-W/MultiMotion#2]
Hello, thanks for your work. I want to apply your dataset, but [this standard contract](https://team.inria.fr/robotlearn/files/2021/11/STANDARD_CONTRACTUAL_CLAUSES_ExPI_Data.pdf) in in project page seems invalid. How can we get it?

**Comment by GUO-W** [comment]
Hi, Thanks for your interest in our work.

Please follow the instruction of [this link](https://zenodo.org/record/5578329#.Yz8VquxBy3J) to download the dataset, and send the request to my supervisor  Dr.Xavier Alameda-Pineda <xavier.alameda-pineda@inria.fr>.

Note that if your institution is in a country that does NOT offer an adequate level of data protection (eg. China, US, etc) , you should follow the instruction and:
(1) ask your supervisor to apply for the dataset if you are a student or post-doc ;
(2) ask the “legal representative of your institution” to sign the [Standard Contractual Clauses](https://team.inria.fr/robotlearn/files/2022/06/STANDARD_CONTRACTUAL_CLAUSES_GDPR_EXPI_Dataset.pdf). This legal representative could be the director of your laboratory or your school. 
Thanks for following this, because many applicants have ignored this request (especially the second one) and wasted time in re-signing the formula.

Sorry for the inconvenience of downloading the dataset. Please do not hesitate to contact if you do not get a reply several days after the application.
